version: "3"

services:
  external:
    container_name: sitevisor
    image: sitevisor-website
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - 8080:8080