site_name: SiteVisor
site_url: https://example.com/
site_description: Digital Twin application
site_author: Grzegorz Piotrowski

repo_url: https://github.com/grzpiotrowski/sitevisor
edit_uri: blob/main/docs/

nav:
  - Overview: index.md
  - User Guide: user-guide/
  - Developer Guide:
    - Local deployment: dev-guide/local-deployment.md
    - Docker deployment: dev-guide/docker-deployment.md
    - Kind deployment: dev-guide/kind-deployment.md
  - Architecture:
    - Architecture Overview: architecture/architecture-overview.md
    - Frontend Overview: architecture/architecture-frontend.md

theme:
  name: material
  features:
    - navigation.expand
